var Mongoose = require('mongoose');
var PersonSchema = new Mongoose.Schema({
	  'email': String,
      'password': String,
      'name': String,
      'points': Number, //negative points mean you should load parent interface!
	  'totalPoints': Number,
	  'numRewardsClaimed': Number,
	  'tasksCompleted': Number
});
exports.Person = Mongoose.model('Person', PersonSchema);


var FamilySchema = new Mongoose.Schema({ 
    //"_id": auto generated by mongodb.
    "controllers":[ //username array
      String
    ],
    "controlees":[ //username arraay
      String    
    ],
    "tasks":[{
      'taskID': String, //identifier of format: assigner-assignee-tasktext
      'assigner': String, //email.
      'assignee': String, //email.
      'taskText': String,
      'taskCompletion': Number,  //a percentage or a number between 0 and 100 would do
      'taskReward': Number,
      'comments':[{
        'text': String,
        'date': Date
      }]
    }],
    "rewards":[{
      'cost': Number,
      'text': String,
    }],
    "notifications":[{
      'text': String,
      'date': Date,
    }]
  // fields are defined here
});



exports.Family = Mongoose.model('Project', FamilySchema);


